namespace :deficiencies do
  desc "Import full list of deficiencies"
  task :import => [:environment] do
    Deficiency.create!([
      {name: "01100 Ships certificates and documents", sort_order: 1, registry_id: 1},
      {name: "01101 Cargo Ship Safety Equipment (including exemption)", sort_order: 1, registry_id: 1},
      {name: "01102 Cargo Ship Safety Construction (including exempt.)", sort_order: 1, registry_id: 1},
      {name: "01103 Passenger Ship Safety (including exemption)", sort_order: 1, registry_id: 1},
      {name: "01104 Cargo Ship Safety Radio (including exemption)", sort_order: 1, registry_id: 1},
      {name: "01105 Cargo Ship Safety (including exemption)", sort_order: 1, registry_id: 1},
      {name: "01106 Document of Compliance (DoC/ ISM)", sort_order: 1, registry_id: 1},
      {name: "01107 Safety Management Certificate (SMC/ ISM)", sort_order: 1, registry_id: 1},
      {name: "01108 Load Lines (including Exemption)", sort_order: 1, registry_id: 1},
      {name: "01109 Decision-Support System for Masters on Pass. Ships", sort_order: 1, registry_id: 1},
      {name: "01110 Authorization for grain carriage", sort_order: 1, registry_id: 1},
      {name: "01111 Liquefied Gases in Bulk (CoF/GC Code)", sort_order: 1, registry_id: 1},
      {name: "01112 Liquefied Gases in Bulk (ICoF/IGC Code)", sort_order: 1, registry_id: 1},
      {name: "01113 Minimum Safe Manning Document", sort_order: 1, registry_id: 1},
      {name: "01114 Dangerous Chemicals in Bulk (CoF/BCH Code)", sort_order: 1, registry_id: 1},
      {name: "01115 Dangerous Chemicals in Bulk (ICoF/IBC Code)", sort_order: 1, registry_id: 1},
      {name: "01116 Operational Limitations for Passenger ships", sort_order: 1, registry_id: 1},
      {name: "01117 International Oil Pollution Prevention (IOPP)", sort_order: 1, registry_id: 1},
      {name: "01118 Pollution Prevention by Noxious Liquid Sub in Bulk", sort_order: 1, registry_id: 1},
      {name: "01119 International Sewage Pollution Prevention Cert.", sort_order: 1, registry_id: 1},
      {name: "01120 Statement of Compliance CAS", sort_order: 1, registry_id: 1},
      {name: "01121 Interim Statement of Compliance CAS", sort_order: 1, registry_id: 1},
      {name: "01122 International ship security certificate", sort_order: 1, registry_id: 1},
      {name: "01123 Continuous synopsis record", sort_order: 1, registry_id: 1},
      {name: "01124 International Air Pollution Cert.", sort_order: 1, registry_id: 1},
      {name: "01125 Engine International Air Pollution Prev. Cert.", sort_order: 1, registry_id: 1},
      {name: "01126 Document of Compliance Dangerous Goods", sort_order: 1, registry_id: 1},
      {name: "01127 Special Purpose Ship Safety", sort_order: 1, registry_id: 1},
      {name: "01128 High Speed Craft Safety and Permit to Operate", sort_order: 1, registry_id: 1},
      {name: "01129 Mobile Offshore Drilling Unit Safety", sort_order: 1, registry_id: 1},
      {name: "01130 INF certificate of fitness", sort_order: 1, registry_id: 1},
      {name: "01131 International Anti-fouling-System Certificate", sort_order: 1, registry_id: 1},
      {name: "01132 Tonnage certificate", sort_order: 1, registry_id: 1},
      {name: "01133 Civil Liability for Oil Pollution Damage Cert.", sort_order: 1, registry_id: 1},
      {name: "01135 Documents for carriage of dangerous goods", sort_order: 1, registry_id: 1},
      {name: "01136 Ballast Water Management Certificate", sort_order: 1, registry_id: 1},
      {name: "01137 Civil liability for Bunker oil pollution damage cert", sort_order: 1, registry_id: 1},
      {name: "01138 International Energy Efficiency Certificate", sort_order: 1, registry_id: 1},
      {name: "01139 Maritime Labour Certificate", sort_order: 1, registry_id: 1},
      {name: "01140 Declaration of Maritime Labour Compliance (Part I and II)", sort_order: 1, registry_id: 1},
      {name: "01141 Liability of carriage of passengers certificate", sort_order: 1, registry_id: 1},
      {name: "01196 SCV code 2010 certificate of inspection", sort_order: 1, registry_id: 1},
      {name: "01197 SCV code 2014 safety certificate", sort_order: 1, registry_id: 1},
      {name: "01198 CCSS safety certificate", sort_order: 1, registry_id: 1},
      {name: "01199 Other (certificates)", sort_order: 1, registry_id: 1},
      {name: "01199XP Ism certification in general", sort_order: 1, registry_id: 1},
      {name: "01201 Certificates for master and officers", sort_order: 1, registry_id: 1},
      {name: "01202 Certificate for rating for watchkeeping", sort_order: 1, registry_id: 1},
      {name: "01203 Certificates for radio personnel", sort_order: 1, registry_id: 1},
      {name: "01204 Certificate for personnel on tankers", sort_order: 1, registry_id: 1},
      {name: "01205 Certificate for personnel on fast rescue boats", sort_order: 1, registry_id: 1},
      {name: "01206 Certificate for advanced fire-fighting", sort_order: 1, registry_id: 1},
      {name: "01207 Doc evidence for personnel on passenger ships", sort_order: 1, registry_id: 1},
      {name: "01208 Doc evidence for personnel on ro-ro passenger ship", sort_order: 1, registry_id: 1},
      {name: "01209 Manning specified by the minimum safe manning doc", sort_order: 1, registry_id: 1},
      {name: "01210 Certificate for medical first aid", sort_order: 1, registry_id: 1},
      {name: "01211 Cert for personnel on survival craft & rescue boat", sort_order: 1, registry_id: 1},
      {name: "01212 Certificate for medical care", sort_order: 1, registry_id: 1},
      {name: "01213 Evidence of Basic Training", sort_order: 1, registry_id: 1},
      {name: "01214 Endorsement by flagstate", sort_order: 1, registry_id: 1},
      {name: "01215 Application for Endorsement by flagstate", sort_order: 1, registry_id: 1},
      {name: "01217 Ship Security Officer Certificate", sort_order: 1, registry_id: 1},
      {name: "01218 Medical certificate", sort_order: 1, registry_id: 1},
      {name: "01219 Training and qualification MLC - Personnal safety training", sort_order: 1, registry_id: 1},
      {name: "01220 Seafarers' employment agreement (SEA)", sort_order: 1, registry_id: 1},
      {name: "01221 Record of employment", sort_order: 1, registry_id: 1},
      {name: "01222 Doc. evidence for personnel on passenger ships", sort_order: 1, registry_id: 1},
      {name: "01223 Security awareness training", sort_order: 1, registry_id: 1},
      {name: "01296 Training certification and watchkeeping for seafar", sort_order: 1, registry_id: 1},
      {name: "01297 SCV boat master license", sort_order: 1, registry_id: 1},
      {name: "01298 SCV boat engineer license", sort_order: 1, registry_id: 1},
      {name: "01299 Other (STCW)", sort_order: 1, registry_id: 1},
      {name: "01299XP Minimum age (STCW)", sort_order: 1, registry_id: 1},
      {name: "01301 Cargo Gear Record Book", sort_order: 1, registry_id: 1},
      {name: "01302 SAR Co-operation plan for pass.ships trad on fixe", sort_order: 1, registry_id: 1},
      {name: "01303 Unattended Machinery Spaces (UMS) Evidence", sort_order: 1, registry_id: 1},
      {name: "01304 Declaration of AFS compliance", sort_order: 1, registry_id: 1},
      {name: "01305 Log-books/compulsory entries", sort_order: 1, registry_id: 1},
      {name: "01306 Shipboard working arrangements", sort_order: 1, registry_id: 1},
      {name: "01307 Maximun hours of work or minimum hours of rest", sort_order: 1, registry_id: 1},
      {name: "01308 Records of seafarers' daily hours of work or rest", sort_order: 1, registry_id: 1},
      {name: "01309 Fire control plan - all", sort_order: 1, registry_id: 1},
      {name: "01310 Signs, indications", sort_order: 1, registry_id: 1},
      {name: "01311 Survey report file", sort_order: 1, registry_id: 1},
      {name: "01312 Thickness measurement report", sort_order: 1, registry_id: 1},
      {name: "01313 Booklet for bulk cargo loading/unloading/stowage", sort_order: 1, registry_id: 1},
      {name: "01314 SOPEP", sort_order: 1, registry_id: 1},
      {name: "01315 Oil record book", sort_order: 1, registry_id: 1},
      {name: "01316 Cargo information", sort_order: 1, registry_id: 1},
      {name: "01317 Cargo record book", sort_order: 1, registry_id: 1},
      {name: "01318 P&A manual", sort_order: 1, registry_id: 1},
      {name: "01319 Shipboard mar.poll.emergency plan for NLS", sort_order: 1, registry_id: 1},
      {name: "01320 Garbage record book", sort_order: 1, registry_id: 1},
      {name: "01321 Endorsement of cargo booklet - Bulk Carriers", sort_order: 1, registry_id: 1},
      {name: "01322 Conformance Test Report", sort_order: 1, registry_id: 1},
      {name: "01323 Fire safety operational booklet", sort_order: 1, registry_id: 1},
      {name: "01324 Material Safety Data Sheets(MSDS)", sort_order: 1, registry_id: 1},
      {name: "01325 ACM statement of compliance (including exemption)", sort_order: 1, registry_id: 1},
      {name: "01326 Stability Information Booklet", sort_order: 1, registry_id: 1},
      {name: "01327 Energy Efficiency Design Index File", sort_order: 1, registry_id: 1},
      {name: "01328 Ship Energy Efficiency Management plan", sort_order: 1, registry_id: 1},
      {name: "01329 Report of inspection on MLC,2006", sort_order: 1, registry_id: 1},
      {name: "01330 Procedure for complaint under MLC,2006", sort_order: 1, registry_id: 1},
      {name: "01331 Collective bargaining agreement", sort_order: 1, registry_id: 1},
      {name: "01332 AIS test report", sort_order: 1, registry_id: 1},
      {name: "01334 STS Operation Plan and Records of STS Operations", sort_order: 1, registry_id: 1},
      {name: "01399 Survey report file (Propulsion)", sort_order: 1, registry_id: 1},
      {name: "02100 Stuctural Safety", sort_order: 1, registry_id: 1},
      {name: "02101 Closing devices/watertight doors", sort_order: 1, registry_id: 1},
      {name: "02102 Damage control plan", sort_order: 1, registry_id: 1},
      {name: "02103 Stability/strength/loading information and instruments", sort_order: 1, registry_id: 1},
      {name: "02104 Information on the A/A-max Ratio (Roro/pass.only)", sort_order: 1, registry_id: 1},
      {name: "02105 Steering gear", sort_order: 1, registry_id: 1},
      {name: "02106 Hull damage impairing seaworthiness", sort_order: 1, registry_id: 1},
      {name: "02107 Ballast, fuel and other tanks", sort_order: 1, registry_id: 1},
      {name: "02108 Electrical installations in general", sort_order: 1, registry_id: 1},
      {name: "02109 Permanent means of access", sort_order: 1, registry_id: 1},
      {name: "02110 Beams, frames, floors-op.damage", sort_order: 1, registry_id: 1},
      {name: "02111 Beams, frames, floors-corrosion", sort_order: 1, registry_id: 1},
      {name: "02112 Hull - corrosion", sort_order: 1, registry_id: 1},
      {name: "02113 Hull - cracking", sort_order: 1, registry_id: 1},
      {name: "02114 Bulkhead -corrosion", sort_order: 1, registry_id: 1},
      {name: "02115 Bulkheads - operational damage", sort_order: 1, registry_id: 1},
      {name: "02116 Bulkheads - cracking", sort_order: 1, registry_id: 1},
      {name: "02117 Decks - corrosion", sort_order: 1, registry_id: 1},
      {name: "02118 Decks - cracking", sort_order: 1, registry_id: 1},
      {name: "02119 Enhanced survey programme (ESP)", sort_order: 1, registry_id: 1},
      {name: "02120 Marking of IMO number", sort_order: 1, registry_id: 1},
      {name: "02121 Cargo area segregation", sort_order: 1, registry_id: 1},
      {name: "02122 Openings to cargo area, doors, ... scuttles", sort_order: 1, registry_id: 1},
      {name: "02123 Wheelhouse -door -window", sort_order: 1, registry_id: 1},
      {name: "02124 Cargo pumproom", sort_order: 1, registry_id: 1},
      {name: "02125 Spaces in cargo areas", sort_order: 1, registry_id: 1},
      {name: "02126 Cargo tank vent system", sort_order: 1, registry_id: 1},
      {name: "02127 Safe access to tanker bows", sort_order: 1, registry_id: 1},
      {name: "02128 Bulk carriers Add.safety measures", sort_order: 1, registry_id: 1},
      {name: "02129 Bulkhead strength", sort_order: 1, registry_id: 1},
      {name: "02130 Triangle mark", sort_order: 1, registry_id: 1},
      {name: "02132 Water level detectors on single hold cargo ships", sort_order: 1, registry_id: 1},
      {name: "02133 Asbestos containing materials", sort_order: 1, registry_id: 1},
      {name: "02134 Loading/Ballast condition", sort_order: 1, registry_id: 1},
      {name: "02196 Construction decks beams hull", sort_order: 1, registry_id: 1},
      {name: "02197 Timber-deck construction", sort_order: 1, registry_id: 1},
      {name: "02198 Cargo tank purging and/or gas-freeing", sort_order: 1, registry_id: 1},
      {name: "02199 Other (Structural conditions)", sort_order: 1, registry_id: 1},
      {name: "02199XP Bulks carriers - additional safety measures", sort_order: 1, registry_id: 1},
      {name: "03100 Load lines", sort_order: 1, registry_id: 1},
      {name: "03101 Overloading", sort_order: 1, registry_id: 1},
      {name: "03102 Freeboard marks", sort_order: 1, registry_id: 1},
      {name: "03103 Railing, gangway, walkway and means for safe passage", sort_order: 1, registry_id: 1},
      {name: "03104 Cargo & other hatchways", sort_order: 1, registry_id: 1},
      {name: "03105 Covers (hatchway-, portable-, tarpaulins, etc.)", sort_order: 1, registry_id: 1},
      {name: "03106 Windows, sidescuttles and deadlights", sort_order: 1, registry_id: 1},
      {name: "03107 Doors", sort_order: 1, registry_id: 1},
      {name: "03108 Ventilators, air pipes, casings", sort_order: 1, registry_id: 1},
      {name: "03109 Machinery space openings", sort_order: 1, registry_id: 1},
      {name: "03110 Manholes/flush scuttles", sort_order: 1, registry_id: 1},
      {name: "03111 Cargo ports and other similar openings", sort_order: 1, registry_id: 1},
      {name: "03112 Scuppers, inlets and discharges", sort_order: 1, registry_id: 1},
      {name: "03113 Bulwarks and freeing ports", sort_order: 1, registry_id: 1},
      {name: "03114 Stowage incl.uprights, lashing,etc. (timber)", sort_order: 1, registry_id: 1},
      {name: "03199 Other (load lines)", sort_order: 1, registry_id: 1},
      {name: "04101 Public address system", sort_order: 1, registry_id: 1},
      {name: "04102 Emergency fire pump and its pipes", sort_order: 1, registry_id: 1},
      {name: "04103 Emergency, lighting,batteries and switches", sort_order: 1, registry_id: 1},
      {name: "04104 Low level lighting in corridors", sort_order: 1, registry_id: 1},
      {name: "04105 Location of emergency installations", sort_order: 1, registry_id: 1},
      {name: "04106 Emergency steering position com./ compass reading", sort_order: 1, registry_id: 1},
      {name: "04107 Emergency towing arrangements and procedures", sort_order: 1, registry_id: 1},
      {name: "04108 Muster list", sort_order: 1, registry_id: 1},
      {name: "04109 Fire drills", sort_order: 1, registry_id: 1},
      {name: "04110 Abandon ship drills", sort_order: 1, registry_id: 1},
      {name: "04111 Damage control plan", sort_order: 1, registry_id: 1},
      {name: "04112 Shipboard Marine Pollution emergency operations", sort_order: 1, registry_id: 1},
      {name: "04113 Water level indicator", sort_order: 1, registry_id: 1},
      {name: "04114 Emergency source of power - Emergency generator", sort_order: 1, registry_id: 1},
      {name: "04115 Safe areas", sort_order: 1, registry_id: 1},
      {name: "04116 Means of communication between safety centre and other control stations", sort_order: 1, registry_id: 1},
      {name: "04117 Functionality of Safety Systems", sort_order: 1, registry_id: 1},
      {name: "05100 Radiocommunication", sort_order: 1, registry_id: 1},
      {name: "05101 Distress messages: obligations and procedures", sort_order: 1, registry_id: 1},
      {name: "05102 Functional requirements", sort_order: 1, registry_id: 1},
      {name: "05103 Main installation", sort_order: 1, registry_id: 1},
      {name: "05104 MF Radio installation", sort_order: 1, registry_id: 1},
      {name: "05105 MF/HF Radio installation", sort_order: 1, registry_id: 1},
      {name: "05106 INMARSAT ship earth station", sort_order: 1, registry_id: 1},
      {name: "05107 Maintenance/duplication of equipment", sort_order: 1, registry_id: 1},
      {name: "05108 Performance standards for radio equipment", sort_order: 1, registry_id: 1},
      {name: "05109 VHF radio installation", sort_order: 1, registry_id: 1},
      {name: "05110 Facilities for reception of marine safety inform.", sort_order: 1, registry_id: 1},
      {name: "05111 Satellite EPIRB 406MHz/1.6GHz", sort_order: 1, registry_id: 1},
      {name: "05112 VHF EPIRB", sort_order: 1, registry_id: 1},
      {name: "05113 SART/AIS-SART", sort_order: 1, registry_id: 1},
      {name: "05114 Reserve source of energy", sort_order: 1, registry_id: 1},
      {name: "05115 Radio log (diary)", sort_order: 1, registry_id: 1},
      {name: "05116 Operation/maintenance", sort_order: 1, registry_id: 1},
      {name: "05118 Operation of GMDSS equipment", sort_order: 1, registry_id: 1},
      {name: "05194 Watch receiver 2182khz", sort_order: 1, registry_id: 1},
      {name: "05195 Reserve installation", sort_order: 1, registry_id: 1},
      {name: "05196 Direction finder", sort_order: 1, registry_id: 1},
      {name: "05197 Vhf station", sort_order: 1, registry_id: 1},
      {name: "05198 Radiotelegraph motorlifeboat", sort_order: 1, registry_id: 1},
      {name: "05198 Radiotelegraph motorlifeboat", sort_order: 1, registry_id: 1},
      {name: "05199 Other (radiocommunication)", sort_order: 1, registry_id: 1},
      {name: "05199XP Portable radio installation", sort_order: 1, registry_id: 1},
      {name: "06101 Cargo Securing Manual", sort_order: 1, registry_id: 1},
      {name: "06102 Grain", sort_order: 1, registry_id: 1},
      {name: "06103 Other cargo/timber/deck/construction", sort_order: 1, registry_id: 1},
      {name: "06104 Lashing material", sort_order: 1, registry_id: 1},
      {name: "06106 Cargo transfer - Tankers", sort_order: 1, registry_id: 1},
      {name: "06107 Cargo operation", sort_order: 1, registry_id: 1},
      {name: "06108 Cargo density declaration", sort_order: 1, registry_id: 1},
      {name: "06109 Loading instrument", sort_order: 1, registry_id: 1},
      {name: "06198 Load/unload/cleaning proced. for cargo spaces tank", sort_order: 1, registry_id: 1},
      {name: "06199 Other (cargo)", sort_order: 1, registry_id: 1},
      {name: "06199XP Loading/unloading plan", sort_order: 1, registry_id: 1},
      {name: "07100 Fire safety measures", sort_order: 1, registry_id: 1},
      {name: "07101 Fire prevention structural integrity", sort_order: 1, registry_id: 1},
      {name: "07102 Inert gas system", sort_order: 1, registry_id: 1},
      {name: "07103 Division - decks,bulkheads and penetrations", sort_order: 1, registry_id: 1},
      {name: "07104 Main Vertical zone", sort_order: 1, registry_id: 1},
      {name: "07105 Fire doors/openings in fire-resisting divisions", sort_order: 1, registry_id: 1},
      {name: "07106 Fire detection and alarm system", sort_order: 1, registry_id: 1},
      {name: "07107 Fire patrol", sort_order: 1, registry_id: 1},
      {name: "07108 Ready availability of fire fighting equipment", sort_order: 1, registry_id: 1},
      {name: "07109 Fixed fire extinguishing installation", sort_order: 1, registry_id: 1},
      {name: "07110 Fire fighting equipment and appliances", sort_order: 1, registry_id: 1},
      {name: "07111 Personal equipment for fire safety", sort_order: 1, registry_id: 1},
      {name: "07112 Emergency Escape Breathing Device and disposition", sort_order: 1, registry_id: 1},
      {name: "07113 Fire pumps and its pipes", sort_order: 1, registry_id: 1},
      {name: "07114 Remote Means of control (opening,pumps,ventilation,etc.) Machinery spaces", sort_order: 1, registry_id: 1},
      {name: "07115 Fire-dampers", sort_order: 1, registry_id: 1},
      {name: "07116 Ventilation (Machinery spaces)", sort_order: 1, registry_id: 1},
      {name: "07117 Jacketed high pressure lines and oil leakage alarm", sort_order: 1, registry_id: 1},
      {name: "07118 International shore-connection", sort_order: 1, registry_id: 1},
      {name: "07120 Means of escape", sort_order: 1, registry_id: 1},
      {name: "07121 Crew alarm", sort_order: 1, registry_id: 1},
      {name: "07122 Fire control plan", sort_order: 1, registry_id: 1},
      {name: "07123 Operation of Fire protection systems", sort_order: 1, registry_id: 1},
      {name: "07124 Maintenance of Fire protection systems", sort_order: 1, registry_id: 1},
      {name: "07125 Evaluation of crew performance (fire drills)", sort_order: 1, registry_id: 1},
      {name: "07126 Oil accumulation in engine room", sort_order: 1, registry_id: 1},
      {name: "07195 Fire doors", sort_order: 1, registry_id: 1},
      {name: "07196 Means of escape (Fire measures)", sort_order: 1, registry_id: 1},
      {name: "07197 Main inlet/outlet vent. System", sort_order: 1, registry_id: 1},
      {name: "07198 Machinery spaces ventilation", sort_order: 1, registry_id: 1},
      {name: "07199 Other (fire safety)", sort_order: 1, registry_id: 1},
      {name: "07199XP Special spaces", sort_order: 1, registry_id: 1},
      {name: "08100 Alarm - signals", sort_order: 1, registry_id: 1},
      {name: "08101 General alarm", sort_order: 1, registry_id: 1},
      {name: "08102 Emergency signal", sort_order: 1, registry_id: 1},
      {name: "08103 Fire alarm", sort_order: 1, registry_id: 1},
      {name: "08104 Steering gear alarm", sort_order: 1, registry_id: 1},
      {name: "08105 Engineers' alarm", sort_order: 1, registry_id: 1},
      {name: "08106 Inert gas alarm", sort_order: 1, registry_id: 1},
      {name: "08107 Machinery controls alarm", sort_order: 1, registry_id: 1},
      {name: "08108 UMS - alarms", sort_order: 1, registry_id: 1},
      {name: "08109 Boiler alarm", sort_order: 1, registry_id: 1},
      {name: "08110 Closing water-tight doors alarm", sort_order: 1, registry_id: 1},
      {name: "08198 General emergency alarm", sort_order: 1, registry_id: 1},
      {name: "08199 Other (alarms)", sort_order: 1, registry_id: 1},
      {name: "08199XP Auto alarm", sort_order: 1, registry_id: 1},
      {name: "09100 Crew and accommodation (ILO 147)", sort_order: 1, registry_id: 1},
      {name: "09101 Minimum age", sort_order: 1, registry_id: 1},
      {name: "09102 Dirty, parasites", sort_order: 1, registry_id: 1},
      {name: "09103 Ventilation (Accommodation)", sort_order: 1, registry_id: 1},
      {name: "09104 Heating", sort_order: 1, registry_id: 1},
      {name: "09105 Noise", sort_order: 1, registry_id: 1},
      {name: "09106 Sanitary Facilities", sort_order: 1, registry_id: 1},
      {name: "09107 Drainage", sort_order: 1, registry_id: 1},
      {name: "09108 Lighting (Accommodation)", sort_order: 1, registry_id: 1},
      {name: "09109 Pipes, wires (insulation)", sort_order: 1, registry_id: 1},
      {name: "09110 Electrical devices", sort_order: 1, registry_id: 1},
      {name: "09111 Sickbay", sort_order: 1, registry_id: 1},
      {name: "09112 Medical Equipment", sort_order: 1, registry_id: 1},
      {name: "09113 Access/structure", sort_order: 1, registry_id: 1},
      {name: "09114 Sleeping room", sort_order: 1, registry_id: 1},
      {name: "09115 No direct openings into sleeping rooms cargo/mach.", sort_order: 1, registry_id: 1},
      {name: "09116 Furnishings", sort_order: 1, registry_id: 1},
      {name: "09117 Berth dimensions, etc.", sort_order: 1, registry_id: 1},
      {name: "09118 Clear head", sort_order: 1, registry_id: 1},
      {name: "09119 Messroom (location)", sort_order: 1, registry_id: 1},
      {name: "09120 Clothes locker", sort_order: 1, registry_id: 1},
      {name: "09121 Laundry", sort_order: 1, registry_id: 1},
      {name: "09122 Record of inspection (Accommodation)", sort_order: 1, registry_id: 1},
      {name: "09124 Galley, handlingroom (maintenance)", sort_order: 1, registry_id: 1},
      {name: "09125 Ventilation (Food and catering)", sort_order: 1, registry_id: 1},
      {name: "09126 Lighting (Food and catering)", sort_order: 1, registry_id: 1},
      {name: "09127 Cleanliness", sort_order: 1, registry_id: 1},
      {name: "09128 Provisions quantity", sort_order: 1, registry_id: 1},
      {name: "09129 Provisions quality", sort_order: 1, registry_id: 1},
      {name: "09130 Water, pipes, tanks", sort_order: 1, registry_id: 1},
      {name: "09131 Cold room", sort_order: 1, registry_id: 1},
      {name: "09132 Cold room temperature", sort_order: 1, registry_id: 1},
      {name: "09133 Cold room cleanliness", sort_order: 1, registry_id: 1},
      {name: "09134 Food personal hygiene", sort_order: 1, registry_id: 1},
      {name: "09135 Food temperature", sort_order: 1, registry_id: 1},
      {name: "09136 Food segregation", sort_order: 1, registry_id: 1},
      {name: "09137 Record of inspection (Food and catering)", sort_order: 1, registry_id: 1},
      {name: "09198 Other (crew and accommodation)", sort_order: 1, registry_id: 1},
      {name: "09198XP Flying wires", sort_order: 1, registry_id: 1},
      {name: "09199 Other (food)", sort_order: 1, registry_id: 1},
      {name: "09199XP Food and catering (ILO 147)", sort_order: 1, registry_id: 1},
      {name: "09200 Working space (ILO 147)", sort_order: 1, registry_id: 1},
      {name: "09201 Ventilation (Working spaces)", sort_order: 1, registry_id: 1},
      {name: "09202 Heating", sort_order: 1, registry_id: 1},
      {name: "09203 Lighting (Working spaces)", sort_order: 1, registry_id: 1},
      {name: "09204 Safe means of access", sort_order: 1, registry_id: 1},
      {name: "09205 Safe means of access Shore - Ship", sort_order: 1, registry_id: 1},
      {name: "09206 Safe means of access Deck - hold/tank, etc.", sort_order: 1, registry_id: 1},
      {name: "09207 Obstruction/slipping, etc.", sort_order: 1, registry_id: 1},
      {name: "09208 Protection machinery", sort_order: 1, registry_id: 1},
      {name: "09209 Electrical", sort_order: 1, registry_id: 1},
      {name: "09210 Machinery", sort_order: 1, registry_id: 1},
      {name: "09211 Steam pipes and pressure pipes", sort_order: 1, registry_id: 1},
      {name: "09212 Danger areas", sort_order: 1, registry_id: 1},
      {name: "09213 Gas instruments", sort_order: 1, registry_id: 1},
      {name: "09214 Emergency cleaning devices", sort_order: 1, registry_id: 1},
      {name: "09216 Personal equipment", sort_order: 1, registry_id: 1},
      {name: "09217 Warning notices", sort_order: 1, registry_id: 1},
      {name: "09218 Protection machines/parts", sort_order: 1, registry_id: 1},
      {name: "09219 Pipes, wires (insulation)", sort_order: 1, registry_id: 1},
      {name: "09220 Structural features (ship)", sort_order: 1, registry_id: 1},
      {name: "09221 Entry dangerous spaces", sort_order: 1, registry_id: 1},
      {name: "09223 Gangway, accommodation-ladder", sort_order: 1, registry_id: 1},
      {name: "09224 Stowage of cargo", sort_order: 1, registry_id: 1},
      {name: "09225 Loading and unloading equipment", sort_order: 1, registry_id: 1},
      {name: "09226 Holds and tanks safety", sort_order: 1, registry_id: 1},
      {name: "09227 Ropes and wires", sort_order: 1, registry_id: 1},
      {name: "09228 Anchoring devices", sort_order: 1, registry_id: 1},
      {name: "09229 Winches & capstans", sort_order: 1, registry_id: 1},
      {name: "09230 Adequate lighting - mooring arrangements", sort_order: 1, registry_id: 1},
      {name: "09232 Cleanliness of engine room", sort_order: 1, registry_id: 1},
      {name: "09233 Guards - fencing around dangerous machinery parts", sort_order: 1, registry_id: 1},
      {name: "09234 Night Working for seafarer under the age of 18", sort_order: 1, registry_id: 1},
      {name: "09235 Fitness for duty - work and rest hours", sort_order: 1, registry_id: 1},
      {name: "09236 Legal documentation on work and rest hours", sort_order: 1, registry_id: 1},
      {name: "09237 Fitness for duty - intoxication", sort_order: 1, registry_id: 1},
      {name: "09238 Pending label", sort_order: 1, registry_id: 1},
      {name: "09284 Personal equipment (Working spaces)", sort_order: 1, registry_id: 1},
      {name: "09285 Warning notices (Working spaces)", sort_order: 1, registry_id: 1},
      {name: "09286 Protection machines/parts (Working spaces)", sort_order: 1, registry_id: 1},
      {name: "09287 Pipes,wires (insulation)", sort_order: 1, registry_id: 1},
      {name: "09288 Structural features (Working spaces)", sort_order: 1, registry_id: 1},
      {name: "09289 Entry dangerous spaces (Working spaces)", sort_order: 1, registry_id: 1},
      {name: "09290 Other (working spaces ILO)", sort_order: 1, registry_id: 1},
      {name: "09291 Accident prevention (ILO147)", sort_order: 1, registry_id: 1},
      {name: "09292 Mooring arrangements (ILO 147)", sort_order: 1, registry_id: 1},
      {name: "09293 Safety equipment", sort_order: 1, registry_id: 1},
      {name: "09294 Fireman's outfit (additional)", sort_order: 1, registry_id: 1},
      {name: "09295 Air supplies", sort_order: 1, registry_id: 1},
      {name: "09296 Stretcher", sort_order: 1, registry_id: 1},
      {name: "09297 Other (working space ILO)", sort_order: 1, registry_id: 1},
      {name: "09297XP Medical first aid, oxygen, resuscitation, antidote", sort_order: 1, registry_id: 1},
      {name: "09298 Other (accident prevention)", sort_order: 1, registry_id: 1},
      {name: "09298XP Decontamination shower, eyewash", sort_order: 1, registry_id: 1},
      {name: "09299 Other (mooring)", sort_order: 1, registry_id: 1},
      {name: "09299XP Respiratory protection", sort_order: 1, registry_id: 1},
      {name: "10100 Safety of navigation", sort_order: 1, registry_id: 1},
      {name: "10101 Pilot ladders and hoist/pilot transfer arrangements", sort_order: 1, registry_id: 1},
      {name: "10102 Type approval equipment", sort_order: 1, registry_id: 1},
      {name: "10103 Radar", sort_order: 1, registry_id: 1},
      {name: "10104 Gyro compass", sort_order: 1, registry_id: 1},
      {name: "10105 Magnetic compass", sort_order: 1, registry_id: 1},
      {name: "10106 Compass correction log", sort_order: 1, registry_id: 1},
      {name: "10107 Automatic radar plotting aid (ARPA)", sort_order: 1, registry_id: 1},
      {name: "10108 Direction finder", sort_order: 1, registry_id: 1},
      {name: "10109 Lights, shapes, sound-signals", sort_order: 1, registry_id: 1},
      {name: "10110 Signalling lamp", sort_order: 1, registry_id: 1},
      {name: "10111 Charts", sort_order: 1, registry_id: 1},
      {name: "10112 Electronic charts (ECDIS)", sort_order: 1, registry_id: 1},
      {name: "10113 Automatic Identification System (AIS)", sort_order: 1, registry_id: 1},
      {name: "10114 Voyage data recorder (VDR) / Simplified Voyage data recorder (S-VDR)", sort_order: 1, registry_id: 1},
      {name: "10115 GNSS receiver/terrestrial radio navigation system", sort_order: 1, registry_id: 1},
      {name: "10116 Nautical publications", sort_order: 1, registry_id: 1},
      {name: "10117 Echo sounder", sort_order: 1, registry_id: 1},
      {name: "10118 Speed and distance indicator", sort_order: 1, registry_id: 1},
      {name: "10119 Rudder angle indicator", sort_order: 1, registry_id: 1},
      {name: "10120 Revolution counter", sort_order: 1, registry_id: 1},
      {name: "10121 Variable pitch indicator", sort_order: 1, registry_id: 1},
      {name: "10122 Rate-of-turn indicator", sort_order: 1, registry_id: 1},
      {name: "10123 International code of signals-SOLAS", sort_order: 1, registry_id: 1},
      {name: "10124 Life-saving signals", sort_order: 1, registry_id: 1},
      {name: "10125 Use of the automatic pilot", sort_order: 1, registry_id: 1},
      {name: "10126 Record of drills and steering gear tests", sort_order: 1, registry_id: 1},
      {name: "10127 Voyage or passage plan", sort_order: 1, registry_id: 1},
      {name: "10128 Navigation bridge visibility", sort_order: 1, registry_id: 1},
      {name: "10129 Navigation records", sort_order: 1, registry_id: 1},
      {name: "10131 Homing device", sort_order: 1, registry_id: 1},
      {name: "10132 Communication-SOLAS chap. 5", sort_order: 1, registry_id: 1},
      {name: "10133 Bridge operation", sort_order: 1, registry_id: 1},
      {name: "10134 HSC operation", sort_order: 1, registry_id: 1},
      {name: "10135 Monitoring of voyage or passage plan", sort_order: 1, registry_id: 1},
      {name: "10136 Estabilishment of working language onboard", sort_order: 1, registry_id: 1},
      {name: "10137 Long-range identification and tracking system (LRIT)", sort_order: 1, registry_id: 1},
      {name: "10138 BNWAS", sort_order: 1, registry_id: 1},
      {name: "10194 Musters and drills", sort_order: 1, registry_id: 1},
      {name: "10195 Shipborne navigational equipment", sort_order: 1, registry_id: 1},
      {name: "10196 Pilot ladders and mechanical pilot hoists", sort_order: 1, registry_id: 1},
      {name: "10197 Ship reporting systems", sort_order: 1, registry_id: 1},
      {name: "10198 Ship's routeing", sort_order: 1, registry_id: 1},
      {name: "10199 Other (navigation)", sort_order: 1, registry_id: 1},
      {name: "10199XP SOLAS related operational deficiencies", sort_order: 1, registry_id: 1},
      {name: "11100 Life saving appliances", sort_order: 1, registry_id: 1},
      {name: "11101 Lifeboats", sort_order: 1, registry_id: 1},
      {name: "11102 Lifeboat inventory", sort_order: 1, registry_id: 1},
      {name: "11103 Stowage and provision of Lifeboats", sort_order: 1, registry_id: 1},
      {name: "11104 Rescue boats", sort_order: 1, registry_id: 1},
      {name: "11105 Rescue boat inventory", sort_order: 1, registry_id: 1},
      {name: "11106 Fast Rescue Boats", sort_order: 1, registry_id: 1},
      {name: "11107 Stowage of rescue boats", sort_order: 1, registry_id: 1},
      {name: "11108 Inflatable liferafts", sort_order: 1, registry_id: 1},
      {name: "11109 Rigid liferafts", sort_order: 1, registry_id: 1},
      {name: "11110 Stowage and provision of liferafts", sort_order: 1, registry_id: 1},
      {name: "11111 Marine Evacuation System", sort_order: 1, registry_id: 1},
      {name: "11112 Launching arrangements for survival craft", sort_order: 1, registry_id: 1},
      {name: "11113 Launching arrangements for rescue boats", sort_order: 1, registry_id: 1},
      {name: "11114 Helicopter landing and pick-up area", sort_order: 1, registry_id: 1},
      {name: "11115 Means of rescue", sort_order: 1, registry_id: 1},
      {name: "11116 Distress flares", sort_order: 1, registry_id: 1},
      {name: "11117 Lifebuoys incl. provision and disposition", sort_order: 1, registry_id: 1},
      {name: "11118 Lifejackets incl.provision and disposition", sort_order: 1, registry_id: 1},
      {name: "11119 Immersion suits", sort_order: 1, registry_id: 1},
      {name: "11120 Anti-exposure suits", sort_order: 1, registry_id: 1},
      {name: "11121 Thermal Protective Aids", sort_order: 1, registry_id: 1},
      {name: "11122 Radio life-saving appliances", sort_order: 1, registry_id: 1},
      {name: "11123 Emergency equipment for 2-way comm.", sort_order: 1, registry_id: 1},
      {name: "11124 Embarkation arrangement survival craft", sort_order: 1, registry_id: 1},
      {name: "11125 Embarkation arrangements rescue boats", sort_order: 1, registry_id: 1},
      {name: "11126 Means of recovery of life saving appliances", sort_order: 1, registry_id: 1},
      {name: "11127 Buoyant apparatus", sort_order: 1, registry_id: 1},
      {name: "11128 Line-throwing appliance", sort_order: 1, registry_id: 1},
      {name: "11129 Operational readiness of lifesaving appliances", sort_order: 1, registry_id: 1},
      {name: "11130 Evaluation, testing and approval", sort_order: 1, registry_id: 1},
      {name: "11131 On board training and instructions", sort_order: 1, registry_id: 1},
      {name: "11132 Maintenance and inspections", sort_order: 1, registry_id: 1},
      {name: "11134 Operation of Life Saving Appliances", sort_order: 1, registry_id: 1},
      {name: "11135 Maintenance of Life Saving Appliances", sort_order: 1, registry_id: 1},
      {name: "11195 Portable radio app. for surv.craft", sort_order: 1, registry_id: 1},
      {name: "11196 Radiotelegraph instal for surv craf", sort_order: 1, registry_id: 1},
      {name: "11197 Epirb's for survival craft", sort_order: 1, registry_id: 1},
      {name: "11198 2-way radioteleph app for surv craf", sort_order: 1, registry_id: 1},
      {name: "11199 Other (life saving)", sort_order: 1, registry_id: 1},
      {name: "11199XP Marking number capacity", sort_order: 1, registry_id: 1},
      {name: "12101 Stowage/segregation/packaging dangerous goods", sort_order: 1, registry_id: 1},
      {name: "12102 Dangerous liquid chemicals in bulk", sort_order: 1, registry_id: 1},
      {name: "12103 Liquefied gases in bulk", sort_order: 1, registry_id: 1},
      {name: "12104 Dangerous Goods Code", sort_order: 1, registry_id: 1},
      {name: "12105 Temperature control", sort_order: 1, registry_id: 1},
      {name: "12106 Instrumentation", sort_order: 1, registry_id: 1},
      {name: "12107 Fire protection cargo deck area", sort_order: 1, registry_id: 1},
      {name: "12108 Personal protection", sort_order: 1, registry_id: 1},
      {name: "12109 Special requirement", sort_order: 1, registry_id: 1},
      {name: "12110 Tank entry", sort_order: 1, registry_id: 1},
      {name: "12112 Dangerous goods / harmful substances in pack. form", sort_order: 1, registry_id: 1},
      {name: "12199 Other (tankers)", sort_order: 1, registry_id: 1},
      {name: "12199XP Carriage of cargo and dangerous goods", sort_order: 1, registry_id: 1},
      {name: "13100 Propulsion & aux machinery", sort_order: 1, registry_id: 1},
      {name: "13101 Propulsion main engine", sort_order: 1, registry_id: 1},
      {name: "13102 Auxiliary engine", sort_order: 1, registry_id: 1},
      {name: "13103 Gauges,thermometers, etc", sort_order: 1, registry_id: 1},
      {name: "13104 Bilge pumping arrangements", sort_order: 1, registry_id: 1},
      {name: "13105 UMS - Ship", sort_order: 1, registry_id: 1},
      {name: "13106 Insulation wetted through (oil)", sort_order: 1, registry_id: 1},
      {name: "13108 Operation of machinery", sort_order: 1, registry_id: 1},
      {name: "13109 Manuals instructions, etc.", sort_order: 1, registry_id: 1},
      {name: "13199 Other (machinery)", sort_order: 1, registry_id: 1},
      {name: "14100 MARPOL - annex I", sort_order: 1, registry_id: 1},
      {name: "14101 Control of discharge", sort_order: 1, registry_id: 1},
      {name: "14102 Retention of oil on board", sort_order: 1, registry_id: 1},
      {name: "14103 Segregation of oil and water ballast", sort_order: 1, registry_id: 1},
      {name: "14104 Oil filtering equipment", sort_order: 1, registry_id: 1},
      {name: "14105 Pumping, piping and discharge arrangements", sort_order: 1, registry_id: 1},
      {name: "14106 Pump room bottom Protection", sort_order: 1, registry_id: 1},
      {name: "14107 Oil disch. Monitoring and control system", sort_order: 1, registry_id: 1},
      {name: "14108 15 PPM Alarm arrangmts.", sort_order: 1, registry_id: 1},
      {name: "14109 Oil/water interface detector", sort_order: 1, registry_id: 1},
      {name: "14110 Standard disch. conn", sort_order: 1, registry_id: 1},
      {name: "14111 SBT, CBT, COW", sort_order: 1, registry_id: 1},
      {name: "14112 Cow operations and equipment manual", sort_order: 1, registry_id: 1},
      {name: "14113 Double hull construction", sort_order: 1, registry_id: 1},
      {name: "14114 Hydrostatically balanced loading", sort_order: 1, registry_id: 1},
      {name: "14115 Condition assesment scheme", sort_order: 1, registry_id: 1},
      {name: "14116 Pollution report-MARPOL Annex I", sort_order: 1, registry_id: 1},
      {name: "14117 Ship type designation", sort_order: 1, registry_id: 1},
      {name: "14119 Oil and oily mixtures from machinery spaces", sort_order: 1, registry_id: 1},
      {name: "14120 Load, unload & clean proc. for cargo sp.(tankers)", sort_order: 1, registry_id: 1},
      {name: "14121 Suspected of discharge violation", sort_order: 1, registry_id: 1},
      {name: "14122 Oil fuel tank protection", sort_order: 1, registry_id: 1},
      {name: "14123 Accidental oil outflow performance", sort_order: 1, registry_id: 1},
      {name: "14197 Oil tankers, chemical tankers and gas carriers", sort_order: 1, registry_id: 1},
      {name: "14198 Oil/oily mixtures from machinery spaces", sort_order: 1, registry_id: 1},
      {name: "14199 Other (MARPOL Annex I)", sort_order: 1, registry_id: 1},
      {name: "14199XP MARPOL related operational deficiencies", sort_order: 1, registry_id: 1},
      {name: "14200 MARPOL - annex II", sort_order: 1, registry_id: 1},
      {name: "14201 Efficient stripping", sort_order: 1, registry_id: 1},
      {name: "14202 Residue disch.systems", sort_order: 1, registry_id: 1},
      {name: "14203 Tank washing equipm.", sort_order: 1, registry_id: 1},
      {name: "14204 Prohibited discharge of NLS slops", sort_order: 1, registry_id: 1},
      {name: "14205 Cargo heating systems - cat Y substances", sort_order: 1, registry_id: 1},
      {name: "14206 Vent. Procedures/equipment", sort_order: 1, registry_id: 1},
      {name: "14207 Pollution report-MARPOL Annex II", sort_order: 1, registry_id: 1},
      {name: "14208 Ship type designation", sort_order: 1, registry_id: 1},
      {name: "14299 Other MARPOL Annex II", sort_order: 1, registry_id: 1},
      {name: "14300 MARPOL - annexe III", sort_order: 1, registry_id: 1},
      {name: "14301 Packaging", sort_order: 1, registry_id: 1},
      {name: "14302 Marking and labelling", sort_order: 1, registry_id: 1},
      {name: "14303 Documentation (MARPOL Annex III)", sort_order: 1, registry_id: 1},
      {name: "14304 Stowage", sort_order: 1, registry_id: 1},
      {name: "14399 Other MARPOL Annex III", sort_order: 1, registry_id: 1},
      {name: "14402 Sewage treatment plant", sort_order: 1, registry_id: 1},
      {name: "14403 Sewage comminuting and disinfecting system", sort_order: 1, registry_id: 1},
      {name: "14404 Sewage discharge connection", sort_order: 1, registry_id: 1},
      {name: "14499 Other (MARPOL Annex IV)", sort_order: 1, registry_id: 1},
      {name: "14500 MARPOL - annexe V", sort_order: 1, registry_id: 1},
      {name: "14501 Garbage shipboard handling", sort_order: 1, registry_id: 1},
      {name: "14502 Placards", sort_order: 1, registry_id: 1},
      {name: "14503 Garbage management plan", sort_order: 1, registry_id: 1},
      {name: "14599 Other MARPOL Annex V", sort_order: 1, registry_id: 1},
      {name: "14599XP Garbage (MARPOL)", sort_order: 1, registry_id: 1},
      {name: "14601 Technical files and if applicable, monitoring manual", sort_order: 1, registry_id: 1},
      {name: "14602 Record book of engine parameters", sort_order: 1, registry_id: 1},
      {name: "14603 Approval for exhaust gas cleaning system", sort_order: 1, registry_id: 1},
      {name: "14604 Bunker delivery notes", sort_order: 1, registry_id: 1},
      {name: "14605 Type approval certificate of incinerator", sort_order: 1, registry_id: 1},
      {name: "14606 Diesel engine relating to air pollution control", sort_order: 1, registry_id: 1},
      {name: "14607 Quality of fuel oil", sort_order: 1, registry_id: 1},
      {name: "14608 Incinerator incl.operations and operating manual", sort_order: 1, registry_id: 1},
      {name: "14609 Volatile organic compounds in tankers", sort_order: 1, registry_id: 1},
      {name: "14610 Operational procedures for engines or equipment", sort_order: 1, registry_id: 1},
      {name: "14611 Ozone-depleting substances", sort_order: 1, registry_id: 1},
      {name: "14613 Approved method", sort_order: 1, registry_id: 1},
      {name: "14614 Sulphur oxides", sort_order: 1, registry_id: 1},
      {name: "14699 Other MARPOL Annex VI", sort_order: 1, registry_id: 1},
      {name: "14701 AFS supporting documentation", sort_order: 1, registry_id: 1},
      {name: "14702 Logbook entries referring AFS", sort_order: 1, registry_id: 1},
      {name: "14703 Paint condition", sort_order: 1, registry_id: 1},
      {name: "14799 Other AFS", sort_order: 1, registry_id: 1},
      {name: "15100 ISM related deficiencies", sort_order: 1, registry_id: 1},
      {name: "15101 Safety and environment policy", sort_order: 1, registry_id: 1},
      {name: "15102 Company responsibility and authority", sort_order: 1, registry_id: 1},
      {name: "15103 Designated person(s)", sort_order: 1, registry_id: 1},
      {name: "15104 Masters responsibility and authority", sort_order: 1, registry_id: 1},
      {name: "15105 Resources and personnel", sort_order: 1, registry_id: 1},
      {name: "15106 Shipboard operations", sort_order: 1, registry_id: 1},
      {name: "15107 Emergency preparedness", sort_order: 1, registry_id: 1},
      {name: "15108 Reports of non-conf., accidents & hazardous occur.", sort_order: 1, registry_id: 1},
      {name: "15109 Maintenance of the ship and equipment", sort_order: 1, registry_id: 1},
      {name: "15110 Documentation-ISM", sort_order: 1, registry_id: 1},
      {name: "15111 Company verification, review and evaluation", sort_order: 1, registry_id: 1},
      {name: "15112 Certification, verification and control", sort_order: 1, registry_id: 1},
      {name: "15150 ISM", sort_order: 1, registry_id: 1},
      {name: "15199 Other (ISM)", sort_order: 1, registry_id: 1},
      {name: "16101 Security related defects", sort_order: 1, registry_id: 1},
      {name: "16102 Ship security alert system", sort_order: 1, registry_id: 1},
      {name: "16103 Ship security plan", sort_order: 1, registry_id: 1},
      {name: "16104 Ship security officer", sort_order: 1, registry_id: 1},
      {name: "16105 Access control to ship", sort_order: 1, registry_id: 1},
      {name: "16106 Security drills", sort_order: 1, registry_id: 1},
      {name: "16199 Other (Maritime security)", sort_order: 1, registry_id: 1},
      {name: "17197 Other safety in general", sort_order: 1, registry_id: 1},
      {name: "17198 Other (SOLAS operational)", sort_order: 1, registry_id: 1},
      {name: "17198XP Other def. clearly hazardous safety", sort_order: 1, registry_id: 1},
      {name: "17199 Other (MARPOL operational)", sort_order: 1, registry_id: 1},
      {name: "17199XP Other def. not clearly hazardous", sort_order: 1, registry_id: 1},
      {name: "18101 Minimum age", sort_order: 1, registry_id: 1},
      {name: "18102 Night Working", sort_order: 1, registry_id: 1},
      {name: "18103 Medical fitness", sort_order: 1, registry_id: 1},
      {name: "18104 Recruitment and placement service", sort_order: 1, registry_id: 1},
      {name: "18199 Other (Minimum requirements)", sort_order: 1, registry_id: 1},
      {name: "18201 Fitness for duty - work and rest hours", sort_order: 1, registry_id: 1},
      {name: "18202 Legal documentation on work and rest hours", sort_order: 1, registry_id: 1},
      {name: "18203 Wages", sort_order: 1, registry_id: 1},
      {name: "18204 Calculation and payment of wages", sort_order: 1, registry_id: 1},
      {name: "18205 Measures to ensure transmission to seafarer's family", sort_order: 1, registry_id: 1},
      {name: "18299 Other (Conditions of employment)", sort_order: 1, registry_id: 1},
      {name: "18301 Noise, vibration and other ambient factors", sort_order: 1, registry_id: 1},
      {name: "18302 Sanitary Facilities", sort_order: 1, registry_id: 1},
      {name: "18303 Drainage", sort_order: 1, registry_id: 1},
      {name: "18304 Lighting (Accommodation)", sort_order: 1, registry_id: 1},
      {name: "18305 Hospital accomodation (Sickbay)", sort_order: 1, registry_id: 1},
      {name: "18306 Sleeping room, additional spaces", sort_order: 1, registry_id: 1},
      {name: "18307 Direct openings into sleeping rooms cargo/mach.", sort_order: 1, registry_id: 1},
      {name: "18308 Furnishings", sort_order: 1, registry_id: 1},
      {name: "18309 Berth dimensions, etc.", sort_order: 1, registry_id: 1},
      {name: "18310 Minimum headroom", sort_order: 1, registry_id: 1},
      {name: "18311 Messroom and recreational facilities", sort_order: 1, registry_id: 1},
      {name: "18312 Galley, handlingroom (maintenance)", sort_order: 1, registry_id: 1},
      {name: "18313 Cleanliness", sort_order: 1, registry_id: 1},
      {name: "18314 Provisions quantity", sort_order: 1, registry_id: 1},
      {name: "18315 Provisions quality and nutritional value", sort_order: 1, registry_id: 1},
      {name: "18316 Water, pipes, tanks", sort_order: 1, registry_id: 1},
      {name: "18317 Food personal hygiene", sort_order: 1, registry_id: 1},
      {name: "18318 Food temperature", sort_order: 1, registry_id: 1},
      {name: "18319 Food segregation", sort_order: 1, registry_id: 1},
      {name: "18320 Record of inspection (Food and catering)", sort_order: 1, registry_id: 1},
      {name: "18321 Heating, air conditioning and ventilation", sort_order: 1, registry_id: 1},
      {name: "18322 Insulation", sort_order: 1, registry_id: 1},
      {name: "18323 Office", sort_order: 1, registry_id: 1},
      {name: "18324 Cold room, cold room cleanliness, cold room temperature", sort_order: 1, registry_id: 1},
      {name: "18325 Training and qualification of ship's cook", sort_order: 1, registry_id: 1},
      {name: "18326 Laundry, Adequate Locker", sort_order: 1, registry_id: 1},
      {name: "18327 Ventilation (Working spaces)", sort_order: 1, registry_id: 1},
      {name: "18328 Record of inspection", sort_order: 1, registry_id: 1},
      {name: "18399 Other (Accommodation, recreational facilities)", sort_order: 1, registry_id: 1},
      {name: "18401 Medical Equipment, medical chest, medical guide", sort_order: 1, registry_id: 1},
      {name: "18402 Access to on shore medical doctor or dentist", sort_order: 1, registry_id: 1},
      {name: "18403 Standard medical report form", sort_order: 1, registry_id: 1},
      {name: "18404 Medical doctor or person in charge of medical care", sort_order: 1, registry_id: 1},
      {name: "18405 Medical advice by radio or satellite", sort_order: 1, registry_id: 1},
      {name: "18406 Medical care onboard or ashore free of charge", sort_order: 1, registry_id: 1},
      {name: "18407 Lighting (Working spaces)", sort_order: 1, registry_id: 1},
      {name: "18408 Electrical", sort_order: 1, registry_id: 1},
      {name: "18409 Dangerous areas", sort_order: 1, registry_id: 1},
      {name: "18410 Gas instruments", sort_order: 1, registry_id: 1},
      {name: "18411 Emergency cleaning devices", sort_order: 1, registry_id: 1},
      {name: "18412 Personal equipment", sort_order: 1, registry_id: 1},
      {name: "18413 Warning notices", sort_order: 1, registry_id: 1},
      {name: "18414 Protection machines/parts", sort_order: 1, registry_id: 1},
      {name: "18415 Entry dangerous spaces", sort_order: 1, registry_id: 1},
      {name: "18416 Ropes and wires", sort_order: 1, registry_id: 1},
      {name: "18417 Anchoring devices", sort_order: 1, registry_id: 1},
      {name: "18418 Winches & capstans", sort_order: 1, registry_id: 1},
      {name: "18419 Adequate lighting - mooring arrangements", sort_order: 1, registry_id: 1},
      {name: "18420 Cleanliness of engine room", sort_order: 1, registry_id: 1},
      {name: "18421 Guards - fencing around dangerous machinery parts", sort_order: 1, registry_id: 1},
      {name: "18422 Asbestos fibres", sort_order: 1, registry_id: 1},
      {name: "18423 Preventative information", sort_order: 1, registry_id: 1},
      {name: "18424 Steam pipes, pressure pipes, wires (insulation)", sort_order: 1, registry_id: 1},
      {name: "18425 Access / structural features (ship)", sort_order: 1, registry_id: 1},
      {name: "18426 Exposure to harmful levels of ambiant factors", sort_order: 1, registry_id: 1},
      {name: "18427 Ship's occupational safety and health policies and programmes", sort_order: 1, registry_id: 1},
      {name: "18428 On board programme for the prevention of occupational injuries and deaseases", sort_order: 1, registry_id: 1},
      {name: "18429 Procedure for inspection, reporting and correcting unsafe conditions and for
      investigating and reporting on-board occupational accidents", sort_order: 1, registry_id: 1},
      {name: "18430 Ship's safety committee", sort_order: 1, registry_id: 1},
      {name: "18431 Investigation after accident", sort_order: 1, registry_id: 1},
      {name: "18432 Risk evaluation, training and instruction to seafarers", sort_order: 1, registry_id: 1},
      {name: "18499 Other (Health protection, medical care)", sort_order: 1, registry_id: 1}
    ])
  end
end
